# Generated by Django 2.0 on 2018-11-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtype',
            old_name='type_blog',
            new_name='type_name',
        ),
    ]
